# Generated by Django 5.1.3 on 2024-12-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='car_plate',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
