# Generated by Django 5.1.3 on 2024-12-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile_car_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='car_plate',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
